### ISSUE TITLE
Docker Container Running Locally While Using vscode-remote-try-python

### ISSUE THREAD

**Issue by leimao** [microsoft/vscode-remote-try-python#12]
Hello,

I was following the instruction on [https://code.visualstudio.com/docs/remote/containers](https://code.visualstudio.com/docs/remote/containers). However, there are some fundamental issues that I don't understand. From the concept shown in the instruction, it seems that the Docker container is running in the remote server, and the only thing required on our local computer is VS Code and our source code and files (no Docker). However, when I started to run the remote container vscode-remote-try-python, I found a vscode-remote-try-python Docker container was built and run on my local computer. Could you please clarify this? I thought you are hosting the containers on your Azure Cloud for users to test this.

```
$ docker ps -a
CONTAINER ID        IMAGE                                                           COMMAND                  CREATED             STATUS                      PORTS               NAMES
96c0b911a773        vsc-vscode-remote-try-python-41cc2ee6f8cb6b0cee4c350f9a78ef53   "/bin/sh -c 'echo Co…"   2 hours ago         Up About a minute                               interesting_herschel
```

Best,

Lei

**Comment by Chuxel** [comment]
You may be thinking of [VS Codespaces](https://marketplace.visualstudio.com/items?itemName=ms-vsonline.vsonline).  

The Remote - SSH / WSL/ Containers extensions interact with local CLIs. Like VS Code itself, you do not need to use Azure. You can see what is required in the [system requirements](https://code.visualstudio.com/docs/remote/containers#_system-requirements). There are also tips for using a remote docker host [here](https://code.visualstudio.com/docs/remote/containers-advanced#_developing-inside-a-container-on-a-remote-docker-host).

**Comment by leimao** [comment]
> You may be thinking of [VS Codespaces](https://marketplace.visualstudio.com/items?itemName=ms-vsonline.vsonline).
> 
> The Remote - SSH / WSL/ Containers extensions interact with local CLIs. Like VS Code itself, you do not need to use Azure. You can see what is required in the [system requirements](https://code.visualstudio.com/docs/remote/containers#_system-requirements). There are also tips for using a remote docker host [here](https://code.visualstudio.com/docs/remote/containers-advanced#_developing-inside-a-container-on-a-remote-docker-host).

Thank you for the prompt reply @Chuxel . Does that mean we need to have a Docker container built on both the local computer and the remote server in order to use "Visual Studio Code Remote - Containers"? Thank you very much.

**Comment by Chuxel** [comment]
Remote - Containers interacts with the Docker CLI locally to do all work. You can connect the Docker CLI to a remote host and use Remote - Containers with it, but you still need the Docker CLI locally. The Docker daemon, Docker Desktop itself does not need to be running in this case.  In this case, your Dockerfiles would be sent to the remote host for processing.

You will have to change defaults, however, since the default experience uses bind mounts from your local OS.

The [advanced article](https://code.visualstudio.com/docs/remote/containers-advanced#_developing-inside-a-container-on-a-remote-docker-host) I linked explains the setup. It's more complicated, which is why the default setup is geared toward local interactions.

**Comment by leimao** [comment]
I see. So it is actually the local Docker CLI, instead of the VS Code, who is doing all the "forwarding" work. Thank you very much @Chuxel .

**Comment by leimao** [comment]
Closing this "issue".

**Comment by Chuxel** [comment]
Yep - exactly. VS Code does the work of setting itself up and working in a split way, managing extensions, etc.
