### ISSUE TITLE
Large docker image build time and dev container size

### ISSUE THREAD

**Issue by kmehant** [microsoft/vscode-remote-try-python#4]
### Context 
Presently `Visual Studio Code` takes quite some time to build the dev container image from the Dockerfile. The spun up dev container is as large as `~990 MB`. Therefore there is a need for Dockerfile optimization.

**Comment by Chuxel** [comment]
@kmehant Thanks for the contribution in addition to the C++ one!  See my comment here https://github.com/microsoft/vscode-remote-try-cpp/pull/3#issuecomment-497741775 -- there's a few tweaks it suggests.  As I mentioned there, switching to slim could make sense, but need to understand the impact given the intent of a development container.

**Comment by kmehant** [comment]
> @kmehant Thanks for the contribution in addition to the C++ one! See my comment here [microsoft/vscode-remote-try-cpp#3 (comment)](https://github.com/microsoft/vscode-remote-try-cpp/pull/3#issuecomment-497741775) -- there's a few tweaks it suggests. As I mentioned there, switching to slim could make sense, but need to understand the impact given the intent of a development container.

Thanks a lot @Chuxel for spending time in reviewing my PRs. I have seen your [microsoft/vscode-remote-try-cpp#3 (comment)](https://github.com/microsoft/vscode-remote-try-cpp/pull/3#issuecomment-497741775) it gave me good insights.
